apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: catfacts
  name: catfacts
  labels:
    app: catfacts
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: catfacts
  template:
    metadata:
      labels:
        app: catfacts
    spec:
      containers:
        - name: catfacts
          image: csbull55/catfacts:v3
