apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cbull
  name: catfacts
  labels:
    app: catfacts
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: catfacts
  template:
    metadata:
      labels:
        app: catfacts
    spec:
      containers:
        - name: catfacts
          image: csbull55/catfacts:69836ea
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
