apiVersion: v1
kind: Service
metadata:
  name: catfacts-demo
  namespace: catfacts-demo
  labels:
    app: catfacts-demo
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: catfacts-demo
  sessionAffinity: None
  type: ClusterIP